# Generated by Django 5.2.8 on 2025-11-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('total_asientos', models.PositiveBigIntegerField()),
                ('asientos_reservados', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AsientosReservado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.PositiveBigIntegerField()),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('ocupado', 'Ocupado')], default='reservado', max_length=20)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='salas.sala')),
            ],
            options={
                'unique_together': {('sala', 'numero_asiento')},
            },
        ),
    ]
