# Generated by Django 5.1.2 on 2026-03-20 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='reservado',
        ),
    ]
